
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'metabase'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'metabase'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  metabase:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view

vars:
  metabase: # Has to be the project name!
    activity: "{{ source('metabase','activity') }}"
    application_permissions_revision: "{{ source('metabase','application_permissions_revision') }}"
    bookmark_ordering: "{{ source('metabase','bookmark_ordering') }}"
    card_bookmark: "{{ source('metabase','card_bookmark') }}"
    card_label: "{{ source('metabase','card_label') }}"
    collection: "{{ source('metabase','collection') }}"
    collection_bookmark: "{{ source('metabase','collection_bookmark') }}"
    collection_permission_graph_revision: "{{ source('metabase','collection_permission_graph_revision') }}"
    computation_job: "{{ source('metabase','computation_job') }}"
    computation_job_result: "{{ source('metabase','computation_job_result') }}"
    core_session: "{{ source('metabase','core_session') }}"
    core_user: "{{ source('metabase','core_user') }}"
    dashboard_bookmark: "{{ source('metabase','dashboard_bookmark') }}"
    dashboard_favorite: "{{ source('metabase','dashboard_favorite') }}"
    dashboardcard_series: "{{ source('metabase','dashboardcard_series') }}"
    data_migrations: "{{ source('metabase','data_migrations') }}"
    databasechangelog: "{{ source('metabase', 'databasechangelog') }}"
    databasechangeloglock: "{{ source('metabase', 'databasechangeloglock') }}"
    dependency: "{{ source('metabase', 'dependency') }}"
    dimension: "{{ source('metabase', 'dimension') }}"
    group_table_access_policy: "{{ source('metabase', 'group_table_access_policy') }}"
    label: "{{ source('metabase', 'label') }}"
    login_history: "{{ source('metabase', 'login_history') }}"
    metabase_database_internal: "{{ source('metabase', 'metabase_database_internal') }}" # Source is called metabase_database but have to change due to env var conflict
    metabase_field: "{{ source('metabase', 'metabase_field') }}"
    metabase_fieldvalues: "{{ source('metabase', 'metabase_fieldvalues') }}"
    metabase_table: "{{ source('metabase', 'metabase_table') }}"
    metric: "{{ source('metabase', 'metric') }}"
    metric_important_field: "{{ source('metabase', 'metric_important_field') }}"
    moderation_review: "{{ source('metabase', 'moderation_review') }}"
    native_query_snippet: "{{ source('metabase', 'native_query_snippet') }}"
    permissions: "{{ source('metabase', 'permissions') }}"
    permissions_group: "{{ source('metabase', 'permissions_group') }}"
    permissions_group_members: "{{ source('metabase', 'permissions_group_members') }}"
    permissions_revision: "{{ source('metabase', 'permissions_revision') }}"
    persisted_info: "{{ source('metabase', 'persisted_info') }}"
    pulse: "{{ source('metabase', 'pulse') }}"
    pulse_card: "{{ source('metabase', 'pulse_card') }}"
    pulse_channel: "{{ source('metabase', 'pulse_channel') }}"
    pulse_channel_recipient: "{{ source('metabase', 'pulse_channel_recipient') }}"
    qrtz_blob_triggers: "{{ source('metabase', 'qrtz_blob_triggers') }}"
    qrtz_calendars: "{{ source('metabase', 'qrtz_calendars') }}"
    qrtz_cron_triggers: "{{ source('metabase', 'qrtz_cron_triggers') }}"
    qrtz_fired_triggers: "{{ source('metabase', 'qrtz_fired_triggers') }}"
    qrtz_job_details: "{{ source('metabase', 'qrtz_job_details') }}"
    qrtz_locks: "{{ source('metabase', 'qrtz_locks') }}"
    qrtz_paused_trigger_grps: "{{ source('metabase', 'qrtz_paused_trigger_grps') }}"
    qrtz_scheduler_state: "{{ source('metabase', 'qrtz_scheduler_state') }}"
    qrtz_simple_triggers: "{{ source('metabase', 'qrtz_simple_triggers') }}"
    qrtz_simprop_triggers: "{{ source('metabase', 'qrtz_simprop_triggers') }}"
    qrtz_triggers: "{{ source('metabase', 'qrtz_triggers') }}"
    query: "{{ source('metabase', 'query') }}"
    query_cache: "{{ source('metabase', 'query_cache') }}"
    query_execution: "{{ source('metabase', 'query_execution') }}"
    report_card: "{{ source('metabase', 'report_card') }}"
    report_cardfavorite: "{{ source('metabase', 'report_cardfavorite') }}"
    report_dashboard: "{{ source('metabase', 'report_dashboard') }}"
    report_dashboardcard: "{{ source('metabase', 'report_dashboardcard') }}"
    revision: "{{ source('metabase', 'revision') }}"
    secret: "{{ source('metabase', 'secret') }}"
    segment: "{{ source('metabase', 'segment') }}"
    setting: "{{ source('metabase', 'setting') }}"
    task_history: "{{ source('metabase', 'task_history') }}"
    timeline: "{{ source('metabase', 'timeline') }}"
    timeline_event: "{{ source('metabase', 'timeline_event') }}"
    view_log: "{{ source('metabase', 'view_log') }}"
