version: "3.5"
services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "metabase"
    ports:
      - "5432:5432"
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: 5432
      MB_DB_HOST: "database"
      MB_DB_USER: "root"
      MB_DB_PASS: "password"
    ports:
      - "3000:3000"
    depends_on:
      - database

networks:
  default:
    name: dbt-net
