name: pull_request_tests

on: 
  push:
    branches:
      - feat/add-ci-cd

env:
  DBT_PROFILES_DIR: ./ci

jobs:
  pull_request_tests:
    name: pull_request_tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./integration_tests

    steps:
      - name: Check Out
        uses: actions/checkut@v2